# CONOPT 4.39 C++ SDK, shipped with a compiled wrapper and core library.
find_path(CONOPT_INCLUDE_DIR NAMES conopt.hpp HINTS "${CONOPT_DIR}" PATH_SUFFIXES include)
find_library(CONOPT_CPP_LIBRARY NAMES conoptcpp HINTS "${CONOPT_DIR}" PATH_SUFFIXES lib lib64)
find_library(CONOPT_LIBRARY NAMES conopt HINTS "${CONOPT_DIR}" PATH_SUFFIXES lib lib64)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(CONOPT DEFAULT_MSG
    CONOPT_INCLUDE_DIR CONOPT_CPP_LIBRARY CONOPT_LIBRARY)
if(CONOPT_FOUND AND NOT TARGET CONOPT::CONOPT)
    add_library(CONOPT::CONOPT INTERFACE IMPORTED)
    set_target_properties(CONOPT::CONOPT PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${CONOPT_INCLUDE_DIR}"
        INTERFACE_LINK_LIBRARIES "${CONOPT_CPP_LIBRARY};${CONOPT_LIBRARY}")
endif()
mark_as_advanced(CONOPT_INCLUDE_DIR CONOPT_CPP_LIBRARY CONOPT_LIBRARY)
