language: cpp

compiler:
  - gcc
  
matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - gfortran
            - liblapack-dev
            - libmetis-dev

before_script:
  - git clone https://github.com/coin-or/coinbrew
  - cd coinbrew
  - mkdir /home/travis/build/coin-or/SHOT/ThirdParty/Ipopt
  - bash ./coinbrew fetch build Ipopt@3.13 --prefix=/home/travis/build/coin-or/SHOT/ThirdParty/Ipopt --no-prompt --tests none --build-dir=build_ipopt
  - bash ./coinbrew install Ipopt --debug
  - rm build -rf
  - mkdir /home/travis/build/coin-or/SHOT/ThirdParty/Cbc
  - bash ./coinbrew fetch build Cbc@2.10 --prefix=/home/travis/build/coin-or/SHOT/ThirdParty/Cbc --no-prompt --tests none --build-dir=build_cbc --no-third-party
  - bash ./coinbrew install Cbc --debug
  - mkdir /home/travis/build/coin-or/SHOT/build
  - cd /home/travis/build/coin-or/SHOT/build
  - cmake .. -DHAS_CBC=on -DCBC_DIR=/home/travis/build/coin-or/SHOT/ThirdParty/Cbc -DHAS_IPOPT=ON -DIPOPT_DIR=/home/travis/build/coin-or/SHOT/ThirdParty/Ipopt -DHAS_GAMS=off -DHAS_CPLEX=off -DHAS_GUROBI=off -DCOMPILE_TESTS=on -DSPDLOG_STATIC=off

script:
  - make -j5
  - make test

after_script:
