/**
   The Supporting Hyperplane Optimization Toolkit (SHOT).

   @author Andreas Lundell, Åbo Akademi University

   @section LICENSE
   This software is licensed under the Eclipse Public License 2.0.
   Please see the README and LICENSE files for more information.
*/

#pragma once
#include "TaskBase.h"

#include <map>
#include <memory>
#include <set>
#include <string>
#include <vector>

#include "../Structs.h"

namespace SHOT
{
class NLPSolverSHOT;
class NonlinearConstraint;

class TaskPerformBoundTightening : public TaskBase
{
public:
    TaskPerformBoundTightening(EnvironmentPtr envPtr, ProblemPtr source);
    ~TaskPerformBoundTightening() override;
    void run() override;
    std::string getType() override;

    std::shared_ptr<NLPSolverSHOT> POASolver;

private:
    virtual void createPOA();

    // Creates a solver for a convex relaxation of the source problem, whose cuts are used in the outer approximation
    std::shared_ptr<NLPSolverSHOT> createPOASolver(ProblemPtr problem);

    // Solves the problem of the solver within the remaining time of the outer approximation
    void solvePOAProblem(std::shared_ptr<NLPSolverSHOT> solver);

    // Adds the cuts generated by the solver for the convex constraints as linear constraints to the source problem,
    // and records which constraints have gotten cuts
    void addPOACuts(std::shared_ptr<NLPSolverSHOT> solver,
        const std::map<std::string, std::shared_ptr<NonlinearConstraint>>& convexConstraints,
        std::set<std::string>& constraintsWithCuts, int& hyperplaneCounter);

    std::shared_ptr<TaskBase> taskSelectHPPts;

    ProblemPtr sourceProblem;
    ProblemPtr relaxedProblem;
};
} // namespace SHOT